import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import books from '../catalogue.json';
import {SITE_URL} from '../../site-config';
import '../books.css';
export const dynamicParams=false;
export function generateStaticParams(){return books.map(b=>({slug:b.slug}))}
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params,b=books.find(b=>b.slug===slug);if(!b)return {};const title=b.title+' chapter ratings & discussion | ChillyMZ',description='Explore '+b.title+' by '+b.author+' chapter by chapter. View the '+b.chapter_count+'-chapter rating grid, rate what you have read, and join reader discussions.';return {title,description,alternates:{canonical:SITE_URL+'/books/'+b.slug+'/'},openGraph:{title,description,url:SITE_URL+'/books/'+b.slug+'/',type:'website'},twitter:{card:'summary',title,description}}}
export default async function Book({params}:Props){const {slug}=await params,b=books.find(b=>b.slug===slug);if(!b)notFound();const href='/?book='+encodeURIComponent(b.id),url=SITE_URL+'/books/'+b.slug+'/';const schema={'@context':'https://schema.org','@type':'Book',name:b.title,author:{'@type':'Person',name:b.author},url,inLanguage:'en',...(b.cover?{image:b.cover.startsWith('/')?'https://chillymz.github.io'+b.cover:b.cover}:{})};return <div className="seo-books"><header><Link href="/">ChillyMZ <span>●</span></Link><Link href="/books/">All books</Link></header><main id="main-content"><nav aria-label="Breadcrumb"><Link href="/books/">Books</Link> / {b.title}</nav><section className="seo-book-hero">{b.cover&&<img src={b.cover} alt={'Cover of '+b.title+' by '+b.author} width={240} height={360}/>}<div><p className="seo-kicker">CHAPTER RATINGS / CHILLYMZ</p><h1>{b.title} chapter ratings</h1><p>By {b.author} · {b.chapter_count} numbered chapters</p><p>Explore the highs and lows of {b.title} through reader chapter ratings. Open the live grid to see current community scores, save your own ratings, and discuss the book with other readers.</p><Link className="seo-action" href={href}>Open chapter rating grid</Link></div></section><h2>Rate and discuss {b.title}</h2><p>Browse without an account. Sign in to rate the chapters you have read, keep your reading diary, or join a discussion. Scores below are not prefilled: community ratings come from readers.</p><h2>Chapters 1–{b.chapter_count}</h2><p>Select a chapter to open its current rating and discussion.</p><div className="seo-chapters">{Array.from({length:b.chapter_count},(_,i)=><Link key={i} href={href+'&chapter='+(i+1)}>Chapter {i+1}</Link>)}</div>{b.chapter_note&&<details><summary>Chapter numbering and source</summary><p>{b.chapter_note}</p>{b.source_url&&<a href={b.source_url} target="_blank" rel="noopener noreferrer">View chapter-count source (may contain spoilers)</a>}</details>}<h2>More books to explore</h2><div className="seo-related">{books.filter(x=>x.id!==b.id&&x.author===b.author).slice(0,6).map(x=><Link key={x.id} href={'/books/'+x.slug+'/'}>{x.title}</Link>)}<Link href="/books/">Browse all books →</Link></div></main><footer><Link href="/">ChillyMZ</Link><Link href="/privacy/">Privacy</Link><Link href="/terms/">Terms</Link><a href="https://openlibrary.org">Covers: Open Library</a></footer><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,String.fromCharCode(92)+'u003c')}}/></div>}
