import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import {createClient} from 'npm:@supabase/supabase-js@2.117.2';

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const admin=createClient(SUPABASE_URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const db=admin.schema('chillymz');
class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
function cors(req:Request){const origin=req.headers.get('origin')||'';let allow='';try{const u=new URL(origin);if(origin==='https://chillymz.github.io'||u.hostname.endsWith('.chatgpt.site')||['localhost','127.0.0.1'].includes(u.hostname))allow=origin}catch{}return {'Access-Control-Allow-Origin':allow||'https://chillymz.github.io','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}}
function json(req:Request,data:unknown,status=200){return Response.json(data,{status,headers:{...cors(req),'Cache-Control':'private, no-store'}})}
function fail(req:Request,e:unknown){console.error(e);return json(req,{error:e instanceof ApiError?e.message:'Admin action failed. Please retry.'},e instanceof ApiError?e.status:503)}
async function owner(req:Request){const h=req.headers.get('authorization')||'';if(!h.toLowerCase().startsWith('bearer '))throw new ApiError(401,'Sign in first.');const {data,error}=await admin.auth.getUser(h.slice(7));if(error||!data.user)throw new ApiError(401,'Your sign-in expired. Please sign in again.');const {data:row,error:ae}=await db.from('administrators').select('auth_user').eq('auth_user',data.user.id).maybeSingle();if(ae)throw ae;if(!row)throw new ApiError(403,'Owner access required.');return data.user.id}
async function limit(user:string,scope:string,n=15,seconds=60){const {data,error}=await db.rpc('consume_rate_limit',{p_key:`${user}:${scope}`,p_limit:n,p_seconds:seconds});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row?.allowed)throw new ApiError(429,'Too many requests. Try again later.')}
function validBook(raw:any,i=0){if(!raw||typeof raw!=='object')throw new ApiError(400,`Row ${i+1}: enter book details.`);const title=String(raw.title||'').trim(),author=String(raw.author||'').trim(),chapterCount=Number(raw.chapterCount??raw.count),sourceUrl=String(raw.sourceUrl||'').trim(),edition=String(raw.edition||'Unabridged English novel').trim(),chapterNote=String(raw.chapterNote||'Numbered narrative chapters only.').trim();if(!title||title.length>160||!author||author.length>120||!Number.isInteger(chapterCount)||chapterCount<1||chapterCount>500)throw new ApiError(400,`Row ${i+1}: enter a title, author and chapter count from 1 to 500.`);let u:URL;try{u=new URL(sourceUrl)}catch{throw new ApiError(400,`Row ${i+1}: add a chapter-count source URL.`)}if(u.protocol!=='https:'||u.username||u.password||sourceUrl.length>1000)throw new ApiError(400,`Row ${i+1}: use a valid HTTPS source URL.`);if(edition.length>200||chapterNote.length>600)throw new ApiError(400,`Row ${i+1}: edition or chapter note is too long.`);return {title,author,chapterCount,sourceUrl,edition,chapterNote}}
function key(title:string,author:string){const clean=(s:string)=>s.toLowerCase().normalize('NFKD').replace(/\p{M}/gu,'').replace(/[^\p{L}\p{N}]/gu,'');return clean(title).replace('sorcerersstone','philosophersstone')+'|'+clean(author)}
const row=(title:string,author:string,chapterCount:number,sourceUrl:string,chapterNote='Numbered narrative chapters only.')=>({title,author,chapterCount,sourceUrl,edition:'Unabridged English novel',chapterNote});
const hp="https://en.wikibooks.org/wiki/Muggles%27_Guide_to_Harry_Potter/Contents";
const batch=[
row("Harry Potter and the Philosopher's Stone",'J. K. Rowling',17,hp,"17 numbered chapters. Also published as Harry Potter and the Sorcerer's Stone."),
row('Harry Potter and the Chamber of Secrets','J. K. Rowling',18,hp),row('Harry Potter and the Prisoner of Azkaban','J. K. Rowling',22,hp),row('Harry Potter and the Goblet of Fire','J. K. Rowling',37,hp),row('Harry Potter and the Order of the Phoenix','J. K. Rowling',38,hp),row('Harry Potter and the Half-Blood Prince','J. K. Rowling',30,hp),row('Harry Potter and the Deathly Hallows','J. K. Rowling',36,hp,'36 numbered chapters; the unnumbered epilogue is excluded.'),
row('The Lightning Thief','Rick Riordan',22,'https://meltongblog.wordpress.com/2020/11/13/lightning-thief-book-summary-and-chapter-breakdown/'),row('The Sea of Monsters','Rick Riordan',20,'https://www.supersummary.com/the-sea-of-monsters/teacher-introduction/'),row("The Titan's Curse",'Rick Riordan',20,'https://www.theliteraryjourney.com/en/post/summary-titans-curse'),row('The Battle of the Labyrinth','Rick Riordan',20,'https://www.reddit.com/r/bookclub/comments/15cmslr/discussion_the_battle_of_the_labyrinth_by_rick/'),row('The Last Olympian','Rick Riordan',23,'https://www.thenerdparty.com/throwback-paperback/percy-jackson-and-the-last-olympian-chapters-13-23'),
row("The Magician's Nephew",'C. S. Lewis',15,'https://homework.study.com/explanation/how-many-chapters-are-in-the-magician-s-nephew.html'),row('The Lion, the Witch and the Wardrobe','C. S. Lewis',17,'https://narnia.fandom.com/wiki/The_Lion,_the_Witch_and_the_Wardrobe_(book)'),row('The Horse and His Boy','C. S. Lewis',15,'https://outschool.com/classes/book-club-narnia-5-the-horse-and-his-boy-pyV7deVO'),row('Prince Caspian','C. S. Lewis',15,'https://narnia.fandom.com/wiki/Prince_Caspian_(book)'),row('The Voyage of the Dawn Treader','C. S. Lewis',16,'https://www.frowl.org/dawntreader/bibliographic.html'),row('The Silver Chair','C. S. Lewis',16,'https://americanliterature.com/author/cs-lewis/book/the-silver-chair'),row('The Last Battle','C. S. Lewis',16,'https://bradleysbasement.co.uk/the-chronicles-of-narnia/the-last-battle-book/'),
row('The Hobbit','J. R. R. Tolkien',19,'https://tolkiengateway.net/wiki/The_Hobbit'),row('The Fellowship of the Ring','J. R. R. Tolkien',22,'https://tolkiengateway.net/wiki/The_Fellowship_of_the_Ring','C1–12 = Book I chapters 1–12; C13–22 = Book II chapters 1–10. Prologue and foreword excluded.'),row('The Two Towers','J. R. R. Tolkien',21,'https://tolkiengateway.net/wiki/The_Two_Towers','C1–11 = Book III chapters 1–11; C12–21 = Book IV chapters 1–10.'),row('The Return of the King','J. R. R. Tolkien',19,'https://tolkiengateway.net/wiki/The_Return_of_the_King','C1–10 = Book V chapters 1–10; C11–19 = Book VI chapters 1–9. Appendices excluded.'),row('A Wizard of Earthsea','Ursula K. Le Guin',10,'https://homework.study.com/explanation/how-many-chapters-are-in-a-wizard-of-earthsea.html'),row('The Tombs of Atuan','Ursula K. Le Guin',12,'https://library.hrmtc.com/2024/01/15/the-tombs-of-atuan/','12 numbered chapters; the unnumbered prologue is excluded.')];
async function preview(books:any[]){const {data,error}=await db.from('books').select('id,title,author,status,catalogue_key');if(error)throw error;const keys=new Map((data||[]).map((b:any)=>[b.catalogue_key||key(b.title,b.author),b]));const seen=new Set<string>();return books.map(b=>{const k=key(b.title,b.author),m=keys.get(k),duplicate=!!m||seen.has(k);seen.add(k);return {...b,key:k,duplicate,existingId:m?.id||null,status:m?`Already ${m.status}`:duplicate?'Repeated in this batch':'Ready to import'}})}
async function handler(req:Request){const user=await owner(req),path=new URL(req.url).pathname.split('/').filter(Boolean).pop()||'admin-test';if(path==='admin-test'){if(req.method!=='GET')throw new ApiError(405,'Method not allowed.');return json(req,{allowed:true})}if(path!=='catalogue-import')throw new ApiError(404,'Endpoint not found.');if(req.method==='GET')return json(req,{books:await preview(batch)});if(req.method!=='POST')throw new ApiError(405,'Method not allowed.');await limit(user,'catalogue-import',15,60);if(!req.headers.get('content-type')?.includes('application/json'))throw new ApiError(415,'Send JSON data.');const text=await req.text();if(new TextEncoder().encode(text).length>150000)throw new ApiError(413,'This request is too large.');let d:any;try{d=JSON.parse(text)}catch{throw new ApiError(400,'Invalid form data.')}const source=d.batch==='fantasy-25'?batch:Array.isArray(d.books)?d.books:[];if(!source.length||source.length>50)throw new ApiError(400,'Choose between 1 and 50 books per batch.');const books=source.map((b:any,i:number)=>validBook(b,i)),rows=await preview(books);if(d.action==='preview')return json(req,{books:rows});if(d.action!=='import')throw new ApiError(400,'Choose preview or import.');const ready=rows.filter((b:any)=>!b.duplicate),created=new Date().toISOString();let added=0;for(const b of ready){const {error}=await db.from('books').insert({id:crypto.randomUUID(),owner:user,title:b.title,author:b.author,chapter_count:b.chapterCount,cover_key:'',mime:'',status:'approved',created,catalogue_key:b.key,source_url:b.sourceUrl,edition:b.edition,chapter_note:b.chapterNote});if(error){if(error.code==='23505')continue;throw error}added++}if(ready.length){const {error}=await db.from('moderation_events').insert({id:crypto.randomUUID(),actor:user,action:'catalogue-import',target:d.batch==='fantasy-25'?'fantasy-25':'custom-batch',reason:`Requested ${ready.length} books with empty ratings.`,created});if(error)throw error}return json(req,{added,skipped:books.length-added,books:await preview(books)})}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});try{return await handler(req)}catch(e){return fail(req,e)}});

