import {readJson,limitRequests} from '../../request-guard';
import {headers} from 'next/headers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {storage} from '../../core-store';
import {RequestError,OWNER_EMAIL} from '../../core-service';
import {inspectContent,visibleRows,reviewKey} from '../../moderation';
export const dynamic='force-dynamic';
const response=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'private, no-store'}});
async function user(){const u=await getChatGPTUser(),h=await headers(),id=h.get('oai-authenticated-user-id');if(!u||!id)throw new RequestError(401,'Sign in to read and write reviews.');return {id,name:u.fullName||'Reader',admin:u.email.toLowerCase()===OWNER_EMAIL}}
function fail(e:unknown){return response({error:e instanceof RequestError?e.message:'Could not access reviews. Please retry.'},e instanceof RequestError?e.status:503)}
async function location(book:unknown,chapter:unknown){const {db}=storage();if(typeof book!=='string'||!Number.isInteger(chapter))throw new RequestError(400,'Invalid chapter.');const b=await db.prepare("SELECT chapter_count FROM books WHERE id=? AND status='approved'").bind(book).first();if(!b||Number(chapter)<1||Number(chapter)>b.chapter_count)throw new RequestError(404,'Chapter not found.');return b}
export async function GET(req:Request){try{const u=await user(),url=new URL(req.url),book=url.searchParams.get('book'),chapter=Number(url.searchParams.get('chapter'));await location(book,chapter);const {db}=storage();const rows=await db.prepare("SELECT r.*,COALESCE(p.name,'Reader') AS name,v.score/10.0 AS score FROM chapter_reviews r LEFT JOIN profiles p ON p.id=r.user LEFT JOIN ratings v ON v.user=r.user AND v.book=r.book AND v.chapter=r.chapter WHERE r.book=? AND r.chapter=? ORDER BY r.updated DESC").bind(book,chapter).all();return response({reviews:await visibleRows(rows.results,u.id,'review',r=>reviewKey(r.user,r.book,r.chapter)),user:u})}catch(e){return fail(e)}}
export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin)throw new RequestError(403,'Invalid request origin.');const u=await user(),d=await readJson(req),b=await location(d.book,d.chapter),{db}=storage();await limitRequests(u.id,'chapter-review',20);if(d.action==='delete'){const author=String(d.user||u.id);if(author!==u.id&&!u.admin)throw new RequestError(403,'You can only remove your own review.');await db.prepare('DELETE FROM chapter_reviews WHERE user=? AND book=? AND chapter=?').bind(author,d.book,d.chapter).run();return response({ok:true})}
if(d.action!=='save')throw new RequestError(400,'Unknown action.');const body=String(d.body||'').trim();if(!body||body.length>5000||!Number.isInteger(d.spoiler)||d.spoiler<0||d.spoiler>b.chapter_count)throw new RequestError(400,'Write a review under 5,000 characters and choose a valid spoiler chapter.');const held=await inspectContent(u.id,'review',reviewKey(u.id,d.book,d.chapter),body);await db.prepare('INSERT INTO profiles (id,name,bio) VALUES (?,?,?) ON CONFLICT(id) DO NOTHING').bind(u.id,u.name,'').run();await db.prepare('INSERT INTO chapter_reviews (user,book,chapter,body,spoiler,updated) VALUES (?,?,?,?,?,?) ON CONFLICT(user,book,chapter) DO UPDATE SET body=excluded.body,spoiler=excluded.spoiler,updated=excluded.updated').bind(u.id,d.book,d.chapter,body,d.spoiler,new Date().toISOString()).run();return response({ok:true,held})}catch(e){return fail(e)}}
