const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),ts=require('typescript'),{DatabaseSync}=require('node:sqlite');
test('authenticated submission, owner approval, rating overwrite and durable reload',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'chapterd-test-'));const filename=path.join(dir,'data.sqlite');let sql=new DatabaseSync(filename);
 sql.exec(fs.readFileSync('drizzle/0000_secret_taskmaster.sql','utf8'));
 sql.exec(fs.readFileSync('drizzle/0004_natural_medusa.sql','utf8'));
 sql.exec(fs.readFileSync('drizzle/0006_volatile_rhodey.sql','utf8'));
 let current={id:'reader-1',email:'reader@example.test',name:'Reader'};const objects=new Map();
 const db={prepare(q){return {bind(...args){return {async run(){const r=sql.prepare(q).run(...args);return {meta:{changes:Number(r.changes)}}},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}}}},async all(){return {results:sql.prepare(q).all()}}}}};
 const bucket={async put(key,bytes,meta){objects.set(key,{body:bytes,meta})},async get(key){return objects.get(key)||null}};
 const cache={};function load(file){if(cache[file])return cache[file];const output=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};const req=(s)=>{if(s==='next/headers')return {headers:async()=>new Headers(current?{'oai-authenticated-user-id':current.id}: {})};if(s.endsWith('chatgpt-auth'))return {getChatGPTUser:async()=>current?{email:current.email,fullName:current.name}:null};if(s.endsWith('core-store'))return {storage:()=>({db,bucket})};if(s.endsWith('catalogue-service'))return load('app/catalogue-service.ts');if(s.endsWith('core-service'))return load('app/core-service.ts');if(s.endsWith('request-guard'))return load('app/request-guard.ts');if(s.endsWith('moderation'))return load('app/moderation.ts');throw Error(s)};new Function('require','module','exports',output)(req,module,module.exports);cache[file]=module.exports;return module.exports}
 const api=load('app/api/core/route.ts'),cover=load('app/api/cover/route.ts');
 const post=(body)=>api.POST(new Request('https://example.test/api/core',{method:'POST',headers:{origin:'https://example.test',...(body instanceof FormData?{}:{'content-type':'application/json'})},body:body instanceof FormData?body:JSON.stringify(body)}));
 current=null;assert.equal((await api.GET()).status,200);assert.equal((await post({action:'rate'})).status,401);
 current={id:'reader-1',email:'reader@example.test',name:'Reader'};
 assert.equal((await api.GET()).status,200);
 const form=new FormData(),id='12345678-1234-1234-1234-123456789abc';
 form.set('id',id);form.set('title','Test book');form.set('author','Test author');form.set('chapterCount','12');form.set('cover',new File([Uint8Array.from([137,80,78,71,13,10,26,10,0])],'cover.png',{type:'image/png'}));
 assert.equal((await post(form)).status,200);
 assert.equal((await post({action:'review',book:id,status:'approved'})).status,403);
 assert.equal((await post({action:'rate',book:id,chapter:1,score:9})).status,404);
 current={id:'other',email:'other@example.test',name:'Other'};
 assert.equal((await (await api.GET()).json()).books.length,0);
 assert.equal((await cover.GET(new Request('https://example.test/api/cover?id='+id))).status,404);
 current={id:'owner',email:'owner@example.invalid',name:'Owner'};
 assert.equal((await post({action:'review',book:id,status:'approved'})).status,200);
 current={id:'reader-1',email:'reader@example.test',name:'Reader'};
 assert.equal((await post({action:'profile',name:'Saved reader',bio:'Saved bio'})).status,200);
 assert.equal((await post({action:'rate',book:id,chapter:1,score:9.2})).status,200);
 assert.equal((await post({action:'rate',book:id,chapter:1,score:8.4})).status,200);
 assert.equal((await post({action:'rate',book:id,chapter:13,score:8})).status,400);
 assert.equal((await post({action:'rate',book:id,chapter:1,score:10.1})).status,400);
 current={id:'other',email:'other@example.test',name:'Other'};
 assert.equal((await post({action:'rate',book:id,chapter:1,score:9.6})).status,200);
 sql.close();sql=new DatabaseSync(filename);current={id:'reader-1',email:'reader@example.test',name:'Reader'};
 const saved=await (await api.GET(new Request('https://example.test/api/core?book='+id))).json();
 assert.equal(saved.user.name,'Saved reader');assert.equal(saved.mine.length,1);assert.equal(saved.mine[0].score,8.4);assert.equal(saved.totals[0].average,9);assert.equal(saved.totals[0].count,2);assert.equal(saved.books[0].status,'approved');assert.equal(saved.distribution.reduce((a,r)=>a+r.count,0),2);
 assert.equal((await cover.GET(new Request('https://example.test/api/cover?id='+id))).status,200);
 const forged=new Request('https://example.test/api/core',{method:'POST',headers:{origin:'https://evil.test','content-type':'application/json'},body:JSON.stringify({action:'rate',book:id,chapter:1,score:3})});assert.equal((await api.POST(forged)).status,403);
 sql.close();
});
