import {readJson,limitRequests} from '../../request-guard';
import {headers} from 'next/headers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {storage} from '../../core-store';
import {OWNER_EMAIL,RequestError} from '../../core-service';
import {mayPost,inspectContent,visibleRows,blocked,targetVisible} from '../../moderation';
export const dynamic='force-dynamic';
const reply=(d:unknown,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store'}});
async function who(){const u=await getChatGPTUser(),h=await headers(),id=h.get('oai-authenticated-user-id');if(!u||!id)throw new RequestError(401,'Sign in to join the conversation.');return {id,name:u.fullName||'Reader',admin:u.email.toLowerCase()===OWNER_EMAIL}}
const fail=(e:unknown)=>reply({error:e instanceof RequestError?e.message:'Could not save or load discussions. Please retry.'},e instanceof RequestError?e.status:503);
export async function GET(){try{const u=await who(),{db}=storage();const posts=await db.prepare("SELECT d.*, b.title AS book_title, COALESCE(p.name,'Reader') AS name,(SELECT COUNT(*) FROM votes v WHERE v.post=d.id) AS votes,(SELECT COUNT(*) FROM comments c WHERE c.post=d.id) AS replies,EXISTS(SELECT 1 FROM votes v WHERE v.post=d.id AND v.user=?) AS voted FROM discussions d LEFT JOIN profiles p ON p.id=d.user LEFT JOIN books b ON b.id=d.book ORDER BY d.created DESC LIMIT 200").bind(u.id).all();const comments=await db.prepare("SELECT c.*,COALESCE(p.name,'Reader') AS name FROM comments c LEFT JOIN profiles p ON p.id=c.user WHERE c.post IN (SELECT id FROM discussions ORDER BY created DESC LIMIT 200) ORDER BY c.created").all();const visiblePosts=await visibleRows(posts.results,u.id,'post',r=>r.id);const visibleComments=(await visibleRows(comments.results,u.id,'reply',r=>r.id)).filter(c=>visiblePosts.some(p=>p.id===c.post));return reply({posts:visiblePosts.map(p=>({...p,replies:visibleComments.filter(c=>c.post===p.id).length})),comments:visibleComments,user:u})}catch(e){return fail(e)}}
export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin)throw new RequestError(403,'Invalid request origin.');const u=await who(),{db}=storage();const d=await readJson(req);await limitRequests(u.id,d.action==='post'?'discussion-post':'discussion-action',d.action==='post'?5:30);if(d.action!=='delete')await mayPost(u.id);await db.prepare('INSERT INTO profiles (id,name,bio) VALUES (?,?,?) ON CONFLICT(id) DO NOTHING').bind(u.id,u.name,'').run();
if(d.action==='post'){const title=String(d.title||'').trim(),body=String(d.body||'').trim();if(!title||title.length>160||!body||body.length>5000||!['Book talk','Recommendations','Theories','Questions','Reviews'].includes(d.topic))throw new RequestError(400,'Add a title, topic, and post (up to 5,000 characters).');if(d.book&&!await db.prepare("SELECT id FROM books WHERE id=? AND status='approved'").bind(d.book).first())throw new RequestError(400,'Choose an approved book.');const id=crypto.randomUUID();const held=await inspectContent(u.id,'post',id,title+'\n'+body);await db.prepare('INSERT INTO discussions (id,user,title,body,topic,book,spoiler,created) VALUES (?,?,?,?,?,?,?,?)').bind(id,u.id,title,body,d.topic,d.book||null,d.spoiler?1:0,new Date().toISOString()).run();return reply({id,held})}
const post=await db.prepare('SELECT * FROM discussions WHERE id=?').bind(String(d.post||'')).first();if(!post)throw new RequestError(404,'Discussion not found.');
if(d.action!=='delete'&&(!await targetVisible('post',post.id)||await blocked(u.id,post.user)))throw new RequestError(403,'This discussion is unavailable for interaction.');
if(d.action==='vote'){if(typeof d.value!=='boolean')throw new RequestError(400,'Invalid vote.');await db.prepare(d.value?'INSERT INTO votes (post,user) VALUES (?,?) ON CONFLICT DO NOTHING':'DELETE FROM votes WHERE post=? AND user=?').bind(post.id,u.id).run()}
else if(d.action==='comment'){const body=String(d.body||'').trim();if(!body||body.length>3000)throw new RequestError(400,'Write a reply under 3,000 characters.');const id=crypto.randomUUID();const held=await inspectContent(u.id,'reply',id,body);await db.prepare('INSERT INTO comments (id,post,user,body,created) VALUES (?,?,?,?,?)').bind(id,post.id,u.id,body,new Date().toISOString()).run();return reply({ok:true,held})}
else if(d.action==='delete'){if(post.user!==u.id&&!u.admin)throw new RequestError(403,'Only the author or owner can remove this post.');await db.batch([db.prepare('DELETE FROM votes WHERE post=?').bind(post.id),db.prepare('DELETE FROM comments WHERE post=?').bind(post.id),db.prepare('DELETE FROM discussions WHERE id=?').bind(post.id)])}
else throw new RequestError(400,'Unknown action.');return reply({ok:true})}catch(e){return fail(e)}}
