export type Book={id:string;title:string;author:string;genre:string;description:string;chapters:string[];scores:number[];counts:number[];color:string;cover?:string;year:number;ongoing:boolean;status:'approved'|'pending'|'rejected'};
const names=['The Beginning','The Mark','Ash','The Sword','The Crossing','A Quiet Warning','The Hollow','Bloodline','The Watcher','No Way Back','The Letter','Fault Lines','The First Lie','Unmasked','The Price','Smoke and Glass','The Promise','The Last Door','Aftermath','The Signal','The Reckoning','The Crown','A Name Forgotten','The Night Before','The Severing','The Empty Throne','Undertow','What Remains','Homecoming','When Shadows Stir'];
export const seedBooks:Book[]=[['jace','When Shadows Stir','ChillyMZ','Fantasy','#285044',30],['crown','The Silent Crown','Nora Vale','Mystery','#324f71',24],['salt','A Kingdom of Salt','Elio Voss','Fantasy','#773d46',22],['signal','The Ninth Signal','Mara Grey','Sci-Fi','#59477c',18],['harbor','Harbor After Dark','Maya Chen','Thriller','#2d6875',16],['orchard','The Glass Orchard','Eli Brooks','Horror','#5a6332',12]].map((v,i)=>({id:String(v[0]),title:String(v[1]),author:String(v[2]),genre:String(v[3]),color:String(v[4]),year:2026,ongoing:i>3,status:'approved',description:i===0?'At an academy where blood decides your place, Jace Halloway must decide what belonging is worth.':'A fictional sample title for exploring chapter ratings, reading progress, and reader discussions.',chapters:Array.from({length:Number(v[5])},(_,n)=>names[n]),scores:Array.from({length:Number(v[5])},(_,n)=>i===0?[7.8,8.1,7.6,8.7,8.2,8.5,8.9,8.4,8.8,9.1,8.6,8.9,9.2,8.7,8.5,9,9.3,9.6,6.8,9,9.2,8.9,9.4,9.1,9.7,9.3,9.5,9,9.6,9.4][n]:Math.round((6.3+((n*7+i*3)%33)/10)*10)/10),counts:Array.from({length:Number(v[5])},(_,n)=>i===0&&n===24?421:45+((n*43+i*87)%500))}));
export const people=['ChillyMZ','Maya Chen','Eli Brooks','Nora Vale','Elio Voss','Mara Grey'];
export type Review={id:string;book:string;chapter:number;user:string;text:string;rating:number;spoiler:number;likes:number;reaction?:boolean};
export const seedReviews:Review[]=[{id:'r1',book:'jace',chapter:25,user:'Maya Chen',text:'Every quiet detail finally matters. The payoff feels earned.',rating:5,spoiler:0,likes:84},{id:'r2',book:'jace',chapter:25,user:'Eli Brooks',text:'The reveal changes what the earlier promise meant. I want to reread the opening now.',rating:4.5,spoiler:25,likes:41},{id:'r3',book:'jace',chapter:25,user:'Nora Vale',text:'The next chapter gives this ending a very different meaning.',rating:4,spoiler:26,likes:12},{id:'r4',book:'crown',chapter:18,user:'Mara Grey',text:'One more chapter turned into the whole evening.',rating:5,spoiler:0,likes:19},{id:'r5',book:'jace',chapter:25,user:'Nora Vale',text:'NO WAY.',rating:5,spoiler:25,likes:31,reaction:true}];
export type Entry={key:string;book:string;chapter:number;rating:number;liked:boolean;date:string};
export type ChapterList={id:string;title:string;description:string;user:string;items:{book:string;chapter:number}[];likes:number};
export const seedLists:ChapterList[]=[{id:'l1',title:'Chapters that kept me up past 3AM',description:'The moments that made putting the book down impossible.',user:'Maya Chen',items:[{book:'jace',chapter:25},{book:'crown',chapter:18},{book:'salt',chapter:22}],likes:128},{id:'l2',title:'Best final chapters',description:'Endings worth the journey.',user:'Eli Brooks',items:[{book:'jace',chapter:30},{book:'crown',chapter:24}],likes:62},{id:'l3',title:'Chapters I need to reread',description:'There is more here the second time.',user:'You',items:[{book:'jace',chapter:18}],likes:0}];
