import {storage} from './core-store';
import {RequestError} from './core-service';
export const reviewKey=(user:string,book:string,chapter:number)=>JSON.stringify([user,book,chapter]);
export async function mayPost(user:string){const {db}=storage();const r=await db.prepare('SELECT * FROM restrictions WHERE user=?').bind(user).first();if(r&&r.until>new Date().toISOString())throw new RequestError(403,'Posting is paused until '+r.until+'. '+r.reason+' You can appeal under Safety.');}
export async function blocked(a:string,b:string){const {db}=storage();return !!await db.prepare("SELECT 1 FROM reader_relations WHERE kind='block' AND ((user=? AND other=?) OR (user=? AND other=?))").bind(a,b,b,a).first()}
export async function visibleRows(rows:any[],viewer:string,kind:string,key:(r:any)=>string){const {db}=storage();const cases=await db.prepare("SELECT kind,target FROM moderation_cases WHERE state IN ('held','removed')").all();const relations=await db.prepare("SELECT user,other,kind FROM reader_relations WHERE user=? OR (other=? AND kind='block')").bind(viewer,viewer).all();const hidden=new Set(cases.results.filter((c:any)=>c.kind===kind).map((c:any)=>c.target)),profiles=new Set(cases.results.filter((c:any)=>c.kind==='profile').map((c:any)=>c.target));return rows.filter(r=>!hidden.has(key(r))&&!relations.results.some((x:any)=>(x.user===viewer&&x.other===r.user)||(x.kind==='block'&&x.other===viewer&&x.user===r.user))).map(r=>profiles.has(r.user)?{...r,name:'Reader'}:r)}
export async function targetVisible(kind:string,target:string){const {db}=storage();return !await db.prepare("SELECT id FROM moderation_cases WHERE kind=? AND target=? AND state IN ('held','removed')").bind(kind,target).first()}
export function automaticReason(text:string){if((text.match(/https?:\/\//gi)||[]).length>=5)return 'Link spam';if(/(.)\1{39}/u.test(text))return 'Repeated-character spam';if(/\b(?:kill you|hurt you|your home address|send nudes)\b/i.test(text))return 'Potential threat, privacy violation, or sexual solicitation';return ''}
export async function inspectContent(user:string,kind:string,target:string,text:string){await mayPost(user);const reason=automaticReason(text);if(!reason)return false;const {db}=storage();await db.prepare("INSERT INTO moderation_cases (id,kind,target,author,reporter,reason,snapshot,state,decision,appeal,appeal_state,created) VALUES (?,?,?,?,?,?,?,'held','','','',?)").bind(crypto.randomUUID(),kind,target,user,'automatic',reason,text,new Date().toISOString()).run();return true}
