import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import {createClient} from 'npm:@supabase/supabase-js@2.117.2';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const admin=createClient(SUPABASE_URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}}),db=admin.schema('chillymz');
class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
function cors(req:Request){const origin=req.headers.get('origin')||'';let allow='';try{const u=new URL(origin);if(origin==='https://chillymz.github.io'||u.hostname.endsWith('.chatgpt.site')||['localhost','127.0.0.1'].includes(u.hostname))allow=origin}catch{}return {'Access-Control-Allow-Origin':allow||'https://chillymz.github.io','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}}
function json(req:Request,data:any,status=200){return Response.json(data,{status,headers:{...cors(req),'Cache-Control':'private, no-store'}})}
function token(req:Request){const h=req.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7):''}
async function user(req:Request,optional=false){const t=token(req);if(!t){if(optional)return null;throw new ApiError(401,'Sign in first.')}const {data,error}=await admin.auth.getUser(t);if(error||!data.user){throw new ApiError(401,'Your sign-in expired.')}const {data:link,error:le}=await db.rpc('ensure_reader_profile',{p_auth_user:data.user.id,p_name:String(data.user.user_metadata?.full_name||data.user.email?.split('@')[0]||'Reader').slice(0,80)});if(le)throw le;const {data:adm,error:ae}=await db.from('administrators').select('auth_user').eq('auth_user',data.user.id).maybeSingle();if(ae)throw ae;return {id:String(link),admin:!!adm}}
async function limit(id:string){const {data,error}=await db.rpc('consume_rate_limit',{p_key:`${id}:analytics`,p_limit:60,p_seconds:60});if(error)throw error;const r=Array.isArray(data)?data[0]:data;if(!r?.allowed)throw new ApiError(429,'Too many requests. Try again later.')}
async function handler(req:Request){const u=await user(req,true);if(req.method==='POST'){if(!u)return json(req,{recorded:false});await limit(u.id);if(!req.headers.get('content-type')?.includes('application/json'))throw new ApiError(415,'Send JSON data.');const d=await req.json(),views=['books','book','chapter','community','diary','profile','submissions','admin','safety','privacy','terms','cookies','other'];if(!views.includes(d.view))throw new ApiError(400,'Invalid section.');if(d.loadMs!==null&&(!Number.isInteger(d.loadMs)||d.loadMs<0||d.loadMs>60000))throw new ApiError(400,'Invalid timing.');const day=new Date().toISOString().slice(0,10),{data:r,error}=await db.from('usage_daily').select('*').eq('day',day).eq('view',d.view).maybeSingle();if(error)throw error;const {error:ue}=await db.from('usage_daily').upsert({day,view:d.view,visits:(r?.visits||0)+1,load_count:(r?.load_count||0)+(d.loadMs===null?0:1),load_total:Number(r?.load_total||0)+(d.loadMs||0)},{onConflict:'day,view'});if(ue)throw ue;return json(req,{recorded:true})}if(req.method!=='GET')throw new ApiError(405,'Method not allowed.');if(!u?.admin)throw new ApiError(403,'Owner access required.');const start=new Date(Date.now()-29*86400000).toISOString().slice(0,10);const [{count:books,error:e1},{count:readers,error:e2},{count:ratings,error:e3},{count:discussions,error:e4},{data:daily,error:e5}]=await Promise.all([db.from('books').select('id',{count:'exact',head:true}).eq('status','approved'),db.from('profiles').select('id',{count:'exact',head:true}),db.from('ratings').select('book',{count:'exact',head:true}),db.from('discussions').select('id',{count:'exact',head:true}),db.from('usage_daily').select('*').gte('day',start)]);if(e1||e2||e3||e4||e5)throw e1||e2||e3||e4||e5;const days=new Map<string,any>(),sections=new Map<string,number>();for(const r of daily||[]){const d=days.get(r.day)||{day:r.day,visits:0,samples:0,load_total:0};d.visits+=r.visits;d.samples+=r.load_count;d.load_total+=Number(r.load_total);days.set(r.day,d);sections.set(r.view,(sections.get(r.view)||0)+r.visits)}return json(req,{totals:{books:books||0,readers:readers||0,ratings:ratings||0,discussions:discussions||0},daily:[...days.values()].sort((a,b)=>b.day.localeCompare(a.day)),sections:[...sections].map(([view,visits])=>({view,visits})).sort((a,b)=>b.visits-a.visits)})}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});try{return await handler(req)}catch(e){console.error(e);return json(req,{error:e instanceof ApiError?e.message:'Analytics unavailable.'},e instanceof ApiError?e.status:503)}});

