export function summarizeVisits(events:any[],now=Date.now(),books:Record<string,string>={}){
 const sessions=new Map<string,any>(),people=new Map<string,any>(),sections=new Map<string,any>(),sources=new Map<string,number>();
 const sessionReaders=new Map<string,string>();for(const e of events)if(e.reader)sessionReaders.set(e.session,e.reader);
 for(const e of events){const key=sessionReaders.get(e.session)?'reader:'+sessionReaders.get(e.session):'browser:'+e.visitor;let p=people.get(key);if(!p){p={id:key,label:(key.startsWith('reader:')?'Account ':'Browser ')+key.split(':')[1].slice(0,8),first:e.created,last:e.created,sessions:new Set<string>(),ratings:0};people.set(key,p)}if(e.created<p.first)p.first=e.created;if(e.created>p.last)p.last=e.created;p.sessions.add(e.session);if(e.event==='rating_saved')p.ratings++;
 let s=sessions.get(e.session);if(!s){s={id:e.session,visitor:p.label,key,started:e.created,last:e.created,source:e.source,device:e.device,visibleMs:0,ratings:0,steps:[],lastScreen:e.view};sessions.set(e.session,s)}s.last=e.created;s.visibleMs+=e.durationMs||0;s.lastScreen=e.view;if(e.event==='rating_saved')s.ratings++;
 if(!['heartbeat','exit'].includes(e.event)){s.steps.push({at:e.created,event:e.event,view:e.view,book:e.book?books[e.book]||e.book:null,chapter:e.chapter,code:e.code})}
 const sec=sections.get(e.view)||{view:e.view,views:0,visibleMs:0,exits:0};if(e.event==='view')sec.views++;sec.visibleMs+=e.durationMs||0;sections.set(e.view,sec);
 }
 for(const s of sessions.values()){sources.set(s.source,(sources.get(s.source)||0)+1);const sec=sections.get(s.lastScreen);if(sec)sec.exits++}
 const funnel=['books','book','chapter','signup_started','signup_completed','rating_saved'].map(stage=>({stage,visits:[...sessions.values()].filter(s=>s.steps.some((e:any)=>['books','book','chapter'].includes(stage)?e.event==='view'&&e.view===stage:e.event===stage)).length}));
 const visitors=[...people.values()].map(p=>({...p,sessions:undefined,visits:p.sessions.size,days:new Set([...p.sessions].map(id=>sessions.get(id).started.slice(0,10))).size,history:[...p.sessions].map(id=>sessions.get(id)).sort((a,b)=>b.started.localeCompare(a.started))})).sort((a,b)=>b.last.localeCompare(a.last));
 const retention=[1,7,30].map(days=>{const eligible=visitors.filter(p=>Date.parse(p.first)<=now-days*86400000);return {days,eligible:eligible.length,returned:eligible.filter(p=>p.history.some((s:any)=>{const gap=(Date.parse(s.started.slice(0,10))-Date.parse(p.first.slice(0,10)))/86400000;return gap>=1&&gap<=days})).length}});
 return {totals:{visits:sessions.size,visitors:people.size,returning:visitors.filter(p=>p.visits>1).length,ratingVisits:[...sessions.values()].filter(s=>s.ratings>0).length},funnel,retention,sections:[...sections.values()].sort((a,b)=>b.views-a.views),sources:[...sources].map(([source,visits])=>({source,visits})),errors:events.filter(e=>e.event==='action_error').length,emptySearches:events.filter(e=>e.event==='search_empty').length,visitors:visitors.slice(0,200)};
}
