import {readJson,limitRequests} from '../../request-guard';
import {headers} from 'next/headers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {storage} from '../../core-store';
import {OWNER_EMAIL,RequestError} from '../../core-service';
export const dynamic='force-dynamic';
async function who(){const u=await getChatGPTUser(),h=await headers(),id=h.get('oai-authenticated-user-id');if(!u||!id)throw new RequestError(401,'Sign in to continue.');return {id,admin:u.email.toLowerCase()===OWNER_EMAIL}}
const out=(d:unknown,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store'}});
const fail=(e:unknown)=>out({error:e instanceof RequestError?e.message:'Could not load or save moderation. Please retry.'},e instanceof RequestError?e.status:503);
async function resolve(kind:string,target:string){const {db}=storage();let r:any;if(kind==='post')r=await db.prepare('SELECT user,title,body FROM discussions WHERE id=?').bind(target).first();else if(kind==='reply')r=await db.prepare('SELECT user,body FROM comments WHERE id=?').bind(target).first();else if(kind==='profile'){r=await db.prepare('SELECT id AS user,name AS title,bio AS body FROM profiles WHERE id=?').bind(target).first()}else if(kind==='review'){let a;try{a=JSON.parse(target)}catch{throw new RequestError(400,'Invalid review.')}if(!Array.isArray(a)||a.length!==3)throw new RequestError(400,'Invalid review.');r=await db.prepare('SELECT user,body FROM chapter_reviews WHERE user=? AND book=? AND chapter=?').bind(...a).first()}if(!r)throw new RequestError(404,'Content no longer exists.');return {author:r.user,text:[r.title,r.body].filter(Boolean).join('\n')}}
export async function GET(){try{const u=await who(),{db}=storage();const cases=await db.prepare(u.admin?'SELECT * FROM moderation_cases ORDER BY created DESC LIMIT 300':"SELECT * FROM moderation_cases WHERE author=? ORDER BY created DESC LIMIT 100").bind(...(u.admin?[]:[u.id])).all();const relations=await db.prepare("SELECT r.*,COALESCE(p.name,'Reader') AS name FROM reader_relations r LEFT JOIN profiles p ON r.other=p.id WHERE r.user=?").bind(u.id).all();const restriction=await db.prepare('SELECT * FROM restrictions WHERE user=?').bind(u.id).first();const reports=await db.prepare('SELECT id,kind,reason,state,decision,created FROM moderation_cases WHERE reporter=? ORDER BY created DESC LIMIT 100').bind(u.id).all();return out({user:u,cases:u.admin?cases.results:cases.results.map(({reporter,...c}:any)=>c),relations:relations.results,restriction,reports:reports.results})}catch(e){return fail(e)}}
export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin)throw new RequestError(403,'Invalid request origin.');const u=await who(),{db}=storage(),d=await readJson(req);await limitRequests(u.id,'moderation-action',30);
if(d.action==='relation'){if(!['block','mute'].includes(d.kind)||typeof d.value!=='boolean'||typeof d.other!=='string'||d.other===u.id)throw new RequestError(400,'Invalid reader selection.');if(!await db.prepare('SELECT id FROM profiles WHERE id=?').bind(d.other).first())throw new RequestError(404,'Reader not found.');await db.prepare(d.value?'INSERT INTO reader_relations (user,other,kind) VALUES (?,?,?) ON CONFLICT DO NOTHING':'DELETE FROM reader_relations WHERE user=? AND other=? AND kind=?').bind(u.id,d.other,d.kind).run();return out({ok:true})}
if(d.action==='report'){if(!['Spam','Harassment','Threats','Sexual content','Privacy','Spoilers','Other'].includes(d.reason))throw new RequestError(400,'Choose a report reason.');const target=String(d.target||''),kind=String(d.kind||''),r=await resolve(kind,target);const existing=await db.prepare("SELECT id FROM moderation_cases WHERE kind=? AND target=? AND reporter=? AND state='open'").bind(kind,target,u.id).first();if(existing)return out({ok:true});await db.prepare("INSERT INTO moderation_cases (id,kind,target,author,reporter,reason,snapshot,state,decision,appeal,appeal_state,created) VALUES (?,?,?,?,?,?,?,'open','','','',?)").bind(crypto.randomUUID(),kind,target,r.author,u.id,d.reason,r.text,new Date().toISOString()).run();return out({ok:true})}
const c=await db.prepare('SELECT * FROM moderation_cases WHERE id=?').bind(String(d.id||'')).first();if(!c)throw new RequestError(404,'Case not found.');
if(d.action==='appeal'){const text=String(d.text||'').trim();if(c.author!==u.id)throw new RequestError(403,'Only the affected reader may appeal.');if(!text||text.length>2000||c.appeal_state==='pending'||!['held','removed','warned','suspended'].includes(c.state))throw new RequestError(400,'An appeal must be under 2,000 characters and concern an active decision.');await db.prepare("UPDATE moderation_cases SET appeal=?,appeal_state='pending' WHERE id=?").bind(text,c.id).run();return out({ok:true})}
if(!u.admin)throw new RequestError(403,'Owner access required.');const reason=String(d.reason||'').trim();if(!reason||reason.length>1000)throw new RequestError(400,'Explain the decision in under 1,000 characters.');const allowed=['approve','remove','warn','suspend','restore','uphold'];if(!allowed.includes(d.action))throw new RequestError(400,'Invalid decision.');const commands=[];const state=d.action==='remove'?'removed':d.action==='warn'?(['held','removed'].includes(c.state)?c.state:'warned'):d.action==='suspend'?(['held','removed'].includes(c.state)?c.state:'suspended'):d.action==='uphold'?c.state:'dismissed';
if(d.action==='suspend'){if(![1,7,30].includes(d.days))throw new RequestError(400,'Choose 1, 7, or 30 days.');commands.push(db.prepare('INSERT INTO restrictions (user,until,reason) VALUES (?,?,?) ON CONFLICT(user) DO UPDATE SET until=excluded.until,reason=excluded.reason').bind(c.author,new Date(Date.now()+d.days*86400000).toISOString(),reason))}
if(d.action==='restore')commands.push(db.prepare('DELETE FROM restrictions WHERE user=?').bind(c.author));
if(['approve','restore'].includes(d.action))commands.push(db.prepare("UPDATE moderation_cases SET state='dismissed',decision=?,appeal_state=CASE WHEN appeal<>'' THEN 'accepted' ELSE '' END WHERE kind=? AND target=? AND state IN ('held','removed')").bind(reason,c.kind,c.target));
commands.push(db.prepare("UPDATE moderation_cases SET state=?,decision=?,appeal_state=? WHERE id=?").bind(state,reason,c.appeal?(['approve','restore'].includes(d.action)?'accepted':'rejected'):'',c.id));
commands.push(db.prepare('INSERT INTO moderation_events (id,actor,action,target,reason,created) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),u.id,d.action,c.id,reason,new Date().toISOString()));await db.batch(commands);return out({ok:true})}catch(e){return fail(e)}}
