import {createClient} from 'npm:@supabase/supabase-js@2.117.2';
export const SCHEMA='chillymz';
export const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
export const db=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}).schema(SCHEMA);
export const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
export type User={authId:string;id:string;name:string;admin:boolean};
export function cors(req:Request){const origin=req.headers.get('origin')||'';let allow='';try{const u=new URL(origin);if(origin==='https://chillymz.github.io'||u.hostname.endsWith('.chatgpt.site')||['localhost','127.0.0.1'].includes(u.hostname))allow=origin}catch{}return {'Access-Control-Allow-Origin':allow||'https://chillymz.github.io','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'};}
export function json(req:Request,data:unknown,status=200){return Response.json(data,{status,headers:{...cors(req),'Cache-Control':'private, no-store'}})}
export function fail(req:Request,e:unknown){console.error(e);return json(req,{error:e instanceof ApiError?e.message:'Could not access saved data. Please retry.'},e instanceof ApiError?e.status:503)}
function token(req:Request){const h=req.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7):''}
export async function who(req:Request,optional=false):Promise<User|null>{const t=token(req);if(!t){if(optional)return null;throw new ApiError(401,'Sign in to contribute.')}const {data,error}=await admin.auth.getUser(t);if(error||!data.user){throw new ApiError(401,'Your sign-in expired. Please sign in again.')}const au=data.user;const name=String(au.user_metadata?.full_name||au.user_metadata?.name||au.email?.split('@')[0]||'Reader').slice(0,80);const {data:reader,error:re}=await db.rpc('ensure_reader_profile',{p_auth_user:au.id,p_name:name});if(re)throw re;const {data:adm,error:ae}=await db.from('administrators').select('auth_user').eq('auth_user',au.id).maybeSingle();if(ae)throw ae;const id=String(reader);const {data:profile}=await db.from('profiles').select('name').eq('id',id).maybeSingle();return {authId:au.id,id,name:profile?.name||name,admin:!!adm};}
export async function rateLimit(user:string,scope:string,limit=30,seconds=60){const {data,error}=await db.rpc('consume_rate_limit',{p_key:`${user}:${scope}`,p_limit:limit,p_seconds:seconds});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row?.allowed)throw new ApiError(429,`Too many requests. Try again in ${row?.retry_after||seconds} seconds.`)}
export function validateRating(chapter:unknown,score:unknown,count:number){if(!Number.isInteger(chapter)||Number(chapter)<1||Number(chapter)>count)throw new ApiError(400,'Invalid chapter.');if(typeof score!=='number'||score<0.1||score>10||Math.abs(score*10-Math.round(score*10))>0.00001)throw new ApiError(400,'Use a score from 0.1 to 10 in steps of 0.1.');return Math.round(score*10)}
export function validBook(input:any){const title=String(input.title||'').trim(),author=String(input.author||'').trim(),count=Number(input.chapterCount??input.count);if(!title||title.length>160||!author||author.length>120||!Number.isInteger(count)||count<1||count>500)throw new ApiError(400,'Enter a title, author and whole chapter count from 1 to 500.');return {title,author,count}}
export function coverType(bytes:Uint8Array){if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71&&bytes[4]===13&&bytes[5]===10&&bytes[6]===26&&bytes[7]===10)return 'image/png';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';if(String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP')return 'image/webp';throw new ApiError(400,'Use a PNG, JPEG or WebP cover.')}
export function bookCover(req:Request,b:any){const {owner,cover_key,mime,...rest}=b;if(!cover_key)return {...rest,cover:''};if(/^https:\/\/covers\.openlibrary\.org\/b\/id\/\d+-L\.jpg(?:\?default=false)?$/.test(cover_key))return {...rest,cover:cover_key};if(/^\/covers\/pg\d+\.jpg$/.test(cover_key)){const o=req.headers.get('origin')||'';return {...rest,cover:o==='https://chillymz.github.io'?`${o}/IMDb-website${cover_key}`:`${o}${cover_key}`}}return {...rest,cover:`${SUPABASE_URL}/functions/v1/chillymz-api/cover?id=${encodeURIComponent(b.id)}`}}
export async function mayPost(user:string){const {data,error}=await db.from('restrictions').select('*').eq('user',user).maybeSingle();if(error)throw error;if(data&&data.until>new Date().toISOString())throw new ApiError(403,`Posting is paused until ${data.until}. ${data.reason} You can appeal under Safety.`)}
export function automaticReason(text:string){if((text.match(/https?:\/\//gi)||[]).length>=5)return 'Link spam';if(/(.)\1{39}/u.test(text))return 'Repeated-character spam';if(/\b(?:kill you|hurt you|your home address|send nudes)\b/i.test(text))return 'Potential threat, privacy violation, or sexual solicitation';return ''}
export async function inspectContent(user:string,kind:string,target:string,text:string){await mayPost(user);const reason=automaticReason(text);if(!reason)return false;const {error}=await db.from('moderation_cases').insert({id:crypto.randomUUID(),kind,target,author:user,reporter:'automatic',reason,snapshot:text,state:'held',decision:'',appeal:'',appeal_state:'',created:new Date().toISOString()});if(error)throw error;return true}
export const reviewKey=(user:string,book:string,chapter:number)=>JSON.stringify([user,book,chapter]);
export async function visibility(viewer:string,kind:string,rows:any[],key:(r:any)=>string){const [{data:cases,error:e1},{data:rels,error:e2}]=await Promise.all([db.from('moderation_cases').select('kind,target').in('state',['held','removed']),viewer?db.from('reader_relations').select('user,other,kind').or(`user.eq.${viewer},and(other.eq.${viewer},kind.eq.block)`):Promise.resolve({data:[],error:null} as any)]);if(e1)throw e1;if(e2)throw e2;const hidden=new Set((cases||[]).filter((c:any)=>c.kind===kind).map((c:any)=>c.target)),profiles=new Set((cases||[]).filter((c:any)=>c.kind==='profile').map((c:any)=>c.target));return rows.filter(r=>!hidden.has(key(r))&&!(rels||[]).some((x:any)=>(x.user===viewer&&x.other===r.user)||(x.kind==='block'&&x.other===viewer&&x.user===r.user))).map(r=>profiles.has(r.user)?{...r,name:'Reader'}:r)}
export async function blocked(a:string,b:string){if(!a||!b)return false;const {data,error}=await db.from('reader_relations').select('user').eq('kind','block').or(`and(user.eq.${a},other.eq.${b}),and(user.eq.${b},other.eq.${a})`).limit(1);if(error)throw error;return !!data?.length}
export async function targetVisible(kind:string,target:string){const {data,error}=await db.from('moderation_cases').select('id').eq('kind',kind).eq('target',target).in('state',['held','removed']).limit(1);if(error)throw error;return !data?.length}
export async function parseJson(req:Request,limit=20000){const len=Number(req.headers.get('content-length')||0);if(len>limit)throw new ApiError(413,'This request is too large.');if(!req.headers.get('content-type')?.includes('application/json'))throw new ApiError(415,'Send JSON data.');const text=await req.text();if(new TextEncoder().encode(text).length>limit)throw new ApiError(413,'This request is too large.');try{const v=JSON.parse(text);if(!v||typeof v!=='object'||Array.isArray(v))throw 0;return v}catch{throw new ApiError(400,'Invalid form data.')}}
