"use client";
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Row={title:string;author:string;chapterCount:number;sourceUrl:string;edition:string;chapterNote:string;duplicate:boolean;status:string};
export default function BulkImport({onImported}:{onImported:()=>void}){
 const [rows,setRows]=useState<Row[]>([]),[draft,setDraft]=useState(''),[custom,setCustom]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState(false),[checked,setChecked]=useState(false);
 async function prepared(){setBusy(true);setError('');try{const r=await fetch('/api/catalogue-import',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.books);setCustom(false);setChecked(true)}catch(e){setError(e instanceof Error?e.message:'Could not load batch.')}finally{setBusy(false)}}
 useEffect(()=>{prepared()},[]);
 async function send(action:string){setBusy(true);setError('');try{let body:any={action,batch:'fantasy-25'};if(custom){try{body={action,books:JSON.parse(draft)}}catch{throw Error('Paste a valid JSON array of books.')}}const r=await fetch('/api/catalogue-import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.books);setChecked(true);if(action==='import'){setConfirm(false);setNotice(`${d.added} books published. ${d.skipped} duplicates skipped. No ratings added.`);onImported()}}catch(e){setError(e instanceof Error?e.message:'Import failed. Retry safely.')}finally{setBusy(false)}}
 const ready=rows.filter(b=>!b.duplicate).length;
 return <section className="bulk-import p-panel"><div className="live-heading"><div><small>CATALOGUE TOOLS</small><h1>Bulk book import</h1></div><span>Up to 50 per batch</span></div><p>Preview titles, chapter counts and sources before publishing. Existing books are skipped. New chapters start unrated.</p><div className="p-row"><button disabled={busy} onClick={prepared}>Prepared batch · 25 fantasy books</button><button disabled={busy} onClick={()=>{setCustom(true);setChecked(false);setRows([]);setNotice('')}}>Import your own batch</button></div>
 {custom&&<><label>Book data · JSON<textarea className="bulk-json" value={draft} onChange={e=>{setDraft(e.target.value);setChecked(false)}} placeholder={'[{"title":"Book title","author":"Author","chapterCount":24,"sourceUrl":"https://publisher.example/book","edition":"English novel","chapterNote":"Excludes the prologue."}]'}/></label><button disabled={busy||!draft.trim()} onClick={()=>send('preview')}>Check & preview batch</button></>}
 <p className="p-muted">Covers are not included in this batch. Books use title-and-author cards.</p>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">Checking catalogue…</p>}
 {checked&&<><p><b>{ready} ready</b> · {rows.length-ready} duplicates · {rows.filter(b=>!b.duplicate).reduce((n,b)=>n+b.chapterCount,0)} chapter tiles</p><div className="bulk-rows">{rows.map((b,i)=><article key={i} className="bulk-row"><div><b>{b.title}</b><p>{b.author} · {b.chapterCount} chapters</p><small>{b.edition}</small><p>{b.chapterNote}</p><a href={b.sourceUrl} target="_blank" rel="noopener noreferrer">Chapter-count source ↗</a></div><span className={b.duplicate?'bulk-duplicate':'bulk-ready'}>{b.status}</span></article>)}</div><button className="p-primary" disabled={busy||!ready} onClick={()=>setConfirm(true)}>{ready?`Publish ${ready} books`:'All books already in catalogue'}</button></>}
 <Dialog open={confirm} onOpenChange={v=>!busy&&setConfirm(v)}><DialogContent className="p-dialog"><DialogTitle>Publish {ready} books?</DialogTitle><DialogDescription>The books and numbered chapter grids will be available immediately. No ratings will be created. Duplicates will be skipped.</DialogDescription>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={()=>setConfirm(false)}>Back to preview</button><button className="p-primary" disabled={busy} onClick={()=>send('import')}>{busy?'Publishing…':'Confirm & publish'}</button></DialogContent></Dialog>
 </section>
}
