"use client";
import {useEffect,useState} from 'react';
import {NativeSelect} from '@/components/ui/native-select';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import BookArt from './book-art';
export type CatalogueBook={id:string;title:string;author:string;chapter_count:number;status:string;cover:string;average?:number;votes?:number};
type Result={books:CatalogueBook[];total:number;page:number;pages:number;pageSize:number};
export default function Catalogue({onOpen,onNavigate,onSubmit,onRequest,revision}:{onOpen:(b:CatalogueBook)=>void;onNavigate:(tab:string)=>void;onSubmit:()=>void;onRequest:(query:string)=>void;revision:number}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('Newest'),[page,setPage]=useState(1),[data,setData]=useState<Result|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');const timer=setTimeout(async()=>{try{const r=await fetch('/api/catalogue?'+new URLSearchParams({q:query,sort,page:String(page)}),{signal:abort.signal,cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Could not load books.')}finally{if(!abort.signal.aborted)setLoading(false)}},200);return()=>{clearTimeout(timer);abort.abort()}},[query,sort,page,retry,revision]);
 const showIntro=!query&&page===1;
 return <>{showIntro&&<section className="catalogue-intro" aria-labelledby="catalogue-intro-title"><div><span className="catalogue-kicker">CHAPTER RATINGS</span><h1 id="catalogue-intro-title">Rate every chapter.<br/>Not just the book.</h1><p>See where a story peaks, where it slows down, and how your ratings compare with other readers.</p></div><div className="catalogue-intro-actions"><button className="p-primary" onClick={()=>document.querySelector<HTMLInputElement>('input[type="search"]')?.focus()}>Find a book</button><button onClick={()=>onNavigate('community')}>See community posts</button></div><div className="catalogue-intro-points"><span><b>01</b> Rate chapters from 0.1–10</span><span><b>02</b> Track your reading curve</span><span><b>03</b> Compare with the community</span></div></section>}
 <div className="live-heading catalogue-heading"><h1>{showIntro?'Explore books':'Books'}</h1><span className="p-muted">{data?.total??'…'} {query?'matches':'books'}</span></div><div className="live-search catalogue-search"><label><span className="sr-only">Search books or authors</span><input type="search" placeholder="Search books or authors…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><label><span className="sr-only">Sort books</span><NativeSelect value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}>{['Newest','Popular','Highest rated','Title'].map(s=><option key={s}>{s}</option>)}</NativeSelect></label></div><nav className="catalogue-shortcuts" aria-label="Catalogue shortcuts"><button aria-pressed={sort==='Highest rated'} onClick={()=>{setSort('Highest rated');setPage(1)}}>Top rated</button><button onClick={()=>onNavigate('diary')}>Your charts</button><button onClick={()=>onNavigate('community')}>Community</button></nav>
 {error?<div role="alert" className="p-panel"><h2>Books didn’t load.</h2><p>{error}</p><button onClick={()=>setRetry(n=>n+1)}>Retry</button></div>:loading?<div className="catalogue-loading" role="status" aria-live="polite"><span>Loading books…</span><div className="catalogue-skeletons" aria-hidden="true">{Array.from({length:6},(_,i)=><i key={i}/>)}</div></div>:<><div className="p-books">{data?.books.map(b=><button className="p-tile" key={b.id} onClick={()=>onOpen(b)}><div className="p-jacket"><BookArt book={b}/></div><b>{b.title}</b><small>{b.author} · {b.chapter_count} chapters</small><small>{b.votes?`★ ${b.average?.toFixed(1)} · ${b.votes} ratings`:'Unrated'}</small></button>)}</div>{data?.total===0&&<div className="p-panel catalogue-empty"><h2>{query?'No matching books.':'The first story starts here.'}</h2><p>{query?'Try another title or author, or request the book if it is missing.':'Submit a book to start the catalogue.'}</p>{query?<div className="p-row"><button onClick={()=>setQuery('')}>Clear search</button><button className="p-primary" onClick={()=>onRequest(query)}>Request this book</button></div>:<button className="p-primary" onClick={onSubmit}>Submit a book</button>}</div>}{data&&data.total>0&&<Pagination className="catalogue-pagination" aria-label="Book pages"><PaginationContent><PaginationItem><button disabled={data.page<=1} onClick={()=>{setPage(data.page-1);window.scrollTo({top:0,behavior:'smooth'})}}>← Previous</button></PaginationItem><PaginationItem><span aria-live="polite">Page {data.page} of {data.pages}</span></PaginationItem><PaginationItem><button disabled={data.page>=data.pages} onClick={()=>{setPage(data.page+1);window.scrollTo({top:0,behavior:'smooth'})}}>Next →</button></PaginationItem></PaginationContent></Pagination>}</>}
 </>;
}
