"use client";
import {useEffect,useState} from 'react';
import {NativeSelect} from '@/components/ui/native-select';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import BookArt from './book-art';
export type CatalogueBook={id:string;title:string;author:string;chapter_count:number;status:string;cover:string;average?:number;votes?:number};
type Result={books:CatalogueBook[];total:number;page:number;pages:number;pageSize:number};
export default function Catalogue({onOpen,onNavigate,onSubmit,onRequest,revision}:{onOpen:(b:CatalogueBook)=>void;onNavigate:(tab:string)=>void;onSubmit:()=>void;onRequest:(query:string)=>void;revision:number}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('Newest'),[page,setPage]=useState(1),[data,setData]=useState<Result|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');const timer=setTimeout(async()=>{try{const r=await fetch('/api/catalogue?'+new URLSearchParams({q:query,sort,page:String(page)}),{signal:abort.signal,cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Could not load books.')}finally{if(!abort.signal.aborted)setLoading(false)}},200);return()=>{clearTimeout(timer);abort.abort()}},[query,sort,page,retry,revision]);
 return <><div className="live-heading"><div><small>THE CATALOGUE</small><h1>Explore books, chapter by chapter.</h1></div><span className="p-muted">{data?.total??'…'} {query?'matches':'books'}</span></div><div className="live-search"><label>Search books or authors<input type="search" placeholder="Search for a book…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><label>Sort by<NativeSelect value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}>{['Newest','Popular','Highest rated','Title'].map(s=><option key={s}>{s}</option>)}</NativeSelect></label></div><div className="live-shortcuts"><button onClick={()=>{setSort('Highest rated');setPage(1)}}><b>Top rated</b><small>Reader-rated books</small></button><button onClick={()=>onNavigate('diary')}><b>Your charts</b><small>Chapters you’ve rated</small></button><a href="/demo#page=lists"><b>Chapter lists</b><small>Explore the demo</small></a><button onClick={()=>onNavigate('community')}><b>Community</b><small>Book talk & discussions</small></button></div>
 {error?<div role="alert" className="p-panel"><p>{error}</p><button onClick={()=>setRetry(n=>n+1)}>Retry</button></div>:loading?<p role="status">Loading books…</p>:<><div className="p-books">{data?.books.map(b=><button className="p-tile" key={b.id} onClick={()=>onOpen(b)}><div className="p-jacket"><BookArt book={b}/></div><b>{b.title}</b><small>{b.author} · {b.chapter_count} chapters</small><small>{b.votes?`★ ${b.average?.toFixed(1)} · ${b.votes} ratings`:'Unrated'}</small></button>)}</div>{data?.total===0&&<div className="p-panel"><h2>{query?'No matching books.':'The first story starts here.'}</h2><p>{query?'Try another title or author.':'Submit a book to start the catalogue.'}</p>{query?<button onClick={()=>onRequest(query)}>Request this book</button>:<button onClick={onSubmit}>Submit a book</button>}</div>}{data&&data.total>0&&<Pagination className="catalogue-pagination" aria-label="Book pages"><PaginationContent><PaginationItem><button disabled={data.page<=1} onClick={()=>setPage(data.page-1)}>← Previous</button></PaginationItem><PaginationItem><span aria-live="polite">Page {data.page} of {data.pages}</span></PaginationItem><PaginationItem><button disabled={data.page>=data.pages} onClick={()=>setPage(data.page+1)}>Next →</button></PaginationItem></PaginationContent></Pagination>}</>}
 </>
}
