"use client";
import {signIn,SignInLink} from './sign-in';
import {useEffect,useState} from 'react';
import {NativeSelect} from '@/components/ui/native-select';
import {ReaderSafety} from './safety';
type Review={user:string;name:string;body:string;spoiler:number;updated:string;score:number|null};
type Data={reviews:Review[];user:{id:string;admin:boolean}};
export default function ChapterReviews({book,chapter,count}:{book:string;chapter:number;count:number}){
const [data,setData]=useState<Data|null>(null),[body,setBody]=useState(''),[spoiler,setSpoiler]=useState('0'),[through,setThrough]=useState('0'),[revealed,setRevealed]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[sort,setSort]=useState('Newest'),[remove,setRemove]=useState('');
async function refresh(){const r=await fetch('/api/chapter-reviews?book='+encodeURIComponent(book)+'&chapter='+chapter,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);return d as Data}
useEffect(()=>{let active=true;fetch('/api/chapter-reviews?book='+encodeURIComponent(book)+'&chapter='+chapter,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active){setData(d);const mine=d.reviews.find((r:Review)=>r.user===d.user.id);setBody(mine?.body||'');setSpoiler(String(mine?.spoiler||0))}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[book,chapter]);
async function write(action:string,user?:string){setBusy(true);setError('');try{const r=await fetch('/api/chapter-reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,book,chapter,body,spoiler:Number(spoiler),user})}),d=await r.json();if(!r.ok)throw Error(d.error);await refresh();if(action==='delete'&&user===data?.user.id){setBody('');setSpoiler('0')}setRemove('');setNotice(d.held?'Held for review. Check Safety for the decision or to appeal.':action==='save'?'Review saved.':'Review removed.')}catch(e){setError(e instanceof Error?e.message:'Please retry.')}finally{setBusy(false)}}
return <section className="chapter-reviews"><h3>Chapter reviews</h3><div className="review-controls"><label>Show spoilers through<NativeSelect value={through} onChange={e=>setThrough(e.target.value)}><option value="0">Hide all spoilers</option>{Array.from({length:count},(_,i)=><option key={i} value={i+1}>Chapter {i+1}</option>)}</NativeSelect></label><label>Sort<NativeSelect value={sort} onChange={e=>setSort(e.target.value)}><option>Newest</option><option>Highest rated</option></NativeSelect></label></div>{error&&<p role="alert">{error} <button onClick={()=>refresh().then(()=>setError('')).catch(e=>setError(e.message))}>Retry</button></p>}{!data&&!error&&<p>Loading reviews…</p>}{data?.reviews.length===0&&<p>No reviews yet. What did you think of this chapter?</p>}{[...(data?.reviews||[])].sort((a,b)=>sort==='Highest rated'?(b.score??-1)-(a.score??-1):b.updated.localeCompare(a.updated)).map(r=><article className="chapter-review" key={r.user}><div><b>{r.name}</b>{r.score!==null&&<span> · {r.score.toFixed(1)} / 10</span>}<small> · {new Date(r.updated).toLocaleDateString()}</small></div>{r.spoiler>Number(through)&&!revealed.includes(r.user)?<button className="review-spoiler" onClick={()=>setRevealed([...revealed,r.user])}>Spoilers through Chapter {r.spoiler} · Reveal</button>:<p>{r.body}</p>}{(r.user===data?.user.id||data?.user.admin)&&<button disabled={busy} onClick={()=>setRemove(r.user)}>Remove review</button>}{remove===r.user&&<div role="group" aria-label="Confirm removal"><p>Remove this review?</p><button disabled={busy} onClick={()=>write('delete',r.user)}>Confirm removal</button><button onClick={()=>setRemove('')}>Cancel</button></div>}{data?.user.id&&<ReaderSafety kind="review" target={JSON.stringify([r.user,book,chapter])} author={r.user} onChange={()=>{refresh().catch(e=>setError(e.message))}}/>}</article>)}{data?.user.id?<><h3>{data.reviews.some(r=>r.user===data.user.id)?'Edit your review':'Write a review'}</h3><label>Your thoughts<textarea maxLength={5000} value={body} onChange={e=>setBody(e.target.value)} placeholder="What stood out in this chapter?"/></label><label>This review contains spoilers through<NativeSelect value={spoiler} onChange={e=>setSpoiler(e.target.value)}><option value="0">No spoilers</option>{Array.from({length:count},(_,i)=><option key={i} value={i+1}>Chapter {i+1}</option>)}</NativeSelect></label><button className="p-primary" disabled={busy||!body.trim()} onClick={()=>write('save')}>{busy?'Saving…':'Save review'}</button>{notice&&<p role="status">{notice}</p>}</>:data&&<p><SignInLink>Sign in to write a review</SignInLink></p>}</section>
}
