"use client";
import {signIn,SignInLink} from './sign-in';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {NativeSelect} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import './community.css';
import BookPicker from './book-picker';
import {ReaderSafety} from './safety';
type Post={book_title?:string;id:string;user:string;name:string;title:string;body:string;topic:string;book:string|null;spoiler:number;created:string;votes:number;replies:number;voted:number};
type Reply={user:string;id:string;post:string;name:string;body:string;created:string};
type Feed={posts:Post[];comments:Reply[];user:{id:string;admin:boolean}};
const topics=['Book talk','Recommendations','Theories','Questions','Reviews'];
export default function Community({books}:{books:{id:string;title:string}[]}){
const [feed,setFeed]=useState<Feed|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[compose,setCompose]=useState(false),[selected,setSelected]=useState(''),[filter,setFilter]=useState('All topics'),[sort,setSort]=useState('Newest'),[query,setQuery]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[topic,setTopic]=useState('Book talk'),[book,setBook]=useState(''),[spoiler,setSpoiler]=useState(false),[revealed,setRevealed]=useState<string[]>([]),[comment,setComment]=useState(''),[remove,setRemove]=useState(''),[notice,setNotice]=useState('');
async function refresh(){const r=await fetch('/api/community',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setFeed(d)}
useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
async function save(data:unknown){if(!feed?.user.id){signIn();return false}setBusy(true);setError('');try{const r=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),d=await r.json();if(!r.ok)throw Error(d.error);await refresh();setNotice(d.held?'Held for review. Check Safety for the decision or to appeal.':'Saved.');return true}catch(e){setError(e instanceof Error?e.message:'Please retry.');return false}finally{setBusy(false)}}
const posts=(feed?.posts||[]).filter(p=>(filter==='All topics'||p.topic===filter)&&(!query||(p.title+' '+(p.spoiler?'':p.body)+' '+p.name).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==='Top'?b.votes-a.votes:sort==='Most discussed'?b.replies-a.replies:b.created.localeCompare(a.created));
const current=feed?.posts.find(p=>p.id===selected);
const hidden=(p:Post)=>!!p.spoiler&&!revealed.includes(p.id);
const reveal=(p:Post)=><button className="p-spoiler" onClick={()=>setRevealed([...revealed,p.id])}>Contains spoilers · Reveal discussion</button>;
return <><div className="live-heading community-heading"><div><h1>Community</h1><p>What are you reading?</p></div><button className="p-primary" onClick={()=>{setError('');feed?.user.id?setCompose(true):signIn()}}>+ New post</button></div>{error&&<div role="alert" className="p-panel">{error}<button onClick={()=>refresh().then(()=>setError('')).catch(e=>setError(e.message))}>Retry</button></div>}
{notice&&<p role="status">{notice}</p>}<div className="talk-layout"><section><div className="talk-filters"><input aria-label="Search discussions" placeholder="Search discussions…" value={query} onChange={e=>setQuery(e.target.value)}/><NativeSelect aria-label="Sort discussions" value={sort} onChange={e=>setSort(e.target.value)}>{['Newest','Top','Most discussed'].map(t=><option key={t}>{t}</option>)}</NativeSelect></div><div className="talk-topics" role="group" aria-label="Discussion topics">{['All topics',...topics].map(t=><button key={t} aria-pressed={filter===t} onClick={()=>setFilter(t)}>{t}</button>)}</div>
{!feed&&!error&&<p>Loading discussions…</p>}{feed&&!posts.length&&<div className="p-panel"><h2>{query?'No matching discussions':'A good conversation starts with a reader.'}</h2><p>{query?'Try another search or topic.':'Ask a question, share a theory, or tell us what you’re reading.'}</p><button onClick={()=>feed?.user.id?setCompose(true):signIn()}>Write the first post</button></div>}
{posts.map(p=><article className="talk-post" key={p.id}><div className="talk-vote"><button disabled={busy} aria-label={p.voted?'Remove upvote':'Upvote discussion'} aria-pressed={!!p.voted} onClick={()=>save({action:'vote',post:p.id,value:!p.voted})}>↑</button><b>{p.votes}</b></div><div><div className="talk-meta"><span>{p.topic}</span><span>{p.name} · {new Date(p.created).toLocaleDateString()}</span>{p.book&&<span>{p.book_title||'Book discussion'}</span>}{!!p.spoiler&&<span>Spoilers</span>}</div><button className="talk-title" onClick={()=>{setSelected(p.id);setComment('')}}>{p.title}</button>{hidden(p)?reveal(p):<p className="talk-excerpt">{p.body}</p>}<button className="talk-replies" onClick={()=>{setSelected(p.id);setComment('')}}>{p.replies} {p.replies===1?'reply':'replies'} · Join discussion</button>{feed?.user.id&&<ReaderSafety compact kind="post" target={p.id} author={p.user} onChange={()=>{refresh().catch(e=>setError(e.message))}}/>}</div></article>)}</section><aside className="talk-sidebar"><h3>A place for book people.</h3><p>Discuss a whole book, one chapter, or what to read next.</p><h3>Keep the conversation good</h3><p>Leave spoilers out of titles. Mark plot details as spoilers, and say which chapter you’re discussing.</p><p>Disagree with an opinion without attacking its reader.</p><small>{feed?.posts.length||0} discussions</small></aside></div>
<Dialog open={compose} onOpenChange={v=>!busy&&setCompose(v)}><DialogContent className="p-dialog"><DialogTitle>Start a discussion</DialogTitle><DialogDescription>Give readers something to talk about. Keep the title spoiler-free.</DialogDescription><label>Title<input maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="What book deserves more attention?"/></label><label>Topic<NativeSelect value={topic} onChange={e=>setTopic(e.target.value)}>{topics.map(t=><option key={t}>{t}</option>)}</NativeSelect></label><BookPicker value={book} onChange={setBook}/><label>Your thoughts<textarea maxLength={5000} value={body} onChange={e=>setBody(e.target.value)}/></label><label className="p-toggle"><Checkbox checked={spoiler} onCheckedChange={v=>setSpoiler(v===true)}/>Contains spoilers (including replies)</label>{error&&<p role="alert">{error}</p>}<button className="p-primary" disabled={busy||!title.trim()||!body.trim()} onClick={async()=>{if(await save({action:'post',title,body,topic,book,spoiler})){setCompose(false);setTitle('');setBody('');setSpoiler(false);setBook('');setFilter('All topics');setQuery('');setSort('Newest')}}}>{busy?'Posting…':'Post discussion'}</button></DialogContent></Dialog>
<Dialog open={!!current} onOpenChange={v=>!v&&!busy&&setSelected('')}><DialogContent className="p-dialog"><DialogTitle>{current?.title}</DialogTitle><DialogDescription>{current?.name} · {current?.topic}{current?.spoiler?' · Contains spoilers':''}</DialogDescription>{current&&(hidden(current)?reveal(current):<><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{current.body}</p><h3>Replies</h3>{feed?.comments.filter(c=>c.post===current.id).map(c=><div className="talk-comment" key={c.id}><b>{c.name}</b><small> · {new Date(c.created).toLocaleDateString()}</small><p>{c.body}</p>{feed?.user.id&&<ReaderSafety compact kind="reply" target={c.id} author={c.user} onChange={()=>{refresh().catch(e=>setError(e.message))}}/>}</div>)}{feed?.user.id?<><label>Join the conversation<textarea maxLength={3000} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add your thoughts…"/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy||!comment.trim()} className="p-primary" onClick={async()=>{if(await save({action:'comment',post:current.id,body:comment}))setComment('')}}>{busy?'Saving…':'Post reply'}</button></>:<p><SignInLink>Sign in to reply</SignInLink></p>}</>)}{current&&(feed?.user.admin||feed?.user.id===current.user)&&<button disabled={busy} onClick={()=>setRemove(current.id)}>Remove discussion</button>}</DialogContent></Dialog>
<Dialog open={!!remove} onOpenChange={v=>!v&&!busy&&setRemove('')}><DialogContent className="p-dialog"><DialogTitle>Remove this discussion?</DialogTitle><DialogDescription>This also removes its replies and votes.</DialogDescription>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={()=>setRemove('')}>Keep discussion</button><button disabled={busy} onClick={async()=>{if(await save({action:'delete',post:remove})){setRemove('');setSelected('')}}}>Remove</button></DialogContent></Dialog></>
}
