"use client";
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {NativeSelect} from '@/components/ui/native-select';
async function send(data:unknown){const r=await fetch('/api/moderation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),d=await r.json();if(!r.ok)throw Error(d.error);return d}
export function ReaderSafety({kind,target,author,onChange}:{kind:string;target:string;author:string;onChange:()=>void}){
const [open,setOpen]=useState(false),[reason,setReason]=useState('Spam'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
async function act(data:unknown){setBusy(true);setError('');try{await send(data);setNotice('Saved. You can manage reports, blocks, and mutes under Safety.');onChange()}catch(e){setError(e instanceof Error?e.message:'Please retry.')}finally{setBusy(false)}}
return <><button onClick={()=>{setOpen(true);setNotice('');setError('')}}>Report / reader controls</button><Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="p-dialog"><DialogTitle>Report or manage this reader</DialogTitle><DialogDescription>Reports go to the owner for review. Blocking hides content both ways and prevents interaction with each other’s discussions. Muting hides their content for you.</DialogDescription><label>Reason<NativeSelect value={reason} onChange={e=>setReason(e.target.value)}>{['Spam','Harassment','Threats','Sexual content','Privacy','Spoilers','Other'].map(r=><option key={r}>{r}</option>)}</NativeSelect></label><button disabled={busy} onClick={()=>act({action:'report',kind,target,reason})}>Report this {kind}</button><button disabled={busy} onClick={()=>act({action:'report',kind:'profile',target:author,reason})}>Report reader profile</button><button disabled={busy} onClick={()=>act({action:'relation',kind:'block',other:author,value:true})}>Block reader</button><button disabled={busy} onClick={()=>act({action:'relation',kind:'mute',other:author,value:true})}>Mute reader</button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</DialogContent></Dialog></>
}
type Case={id:string;kind:string;target:string;author:string;reason:string;snapshot:string;state:string;decision:string;appeal:string;appeal_state:string;created:string};
type Data={user:{id:string;admin:boolean};cases:Case[];reports:Case[];relations:{other:string;kind:string;name:string}[];restriction:{until:string;reason:string}|null};
export default function Safety(){
const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[text,setText]=useState<Record<string,string>>({}),[days,setDays]=useState('7'),[filter,setFilter]=useState('Needs review'),[confirm,setConfirm]=useState<{action:string;id:string}|null>(null);
async function refresh(){const r=await fetch('/api/moderation',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}
useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
async function act(d:unknown){setBusy(true);setError('');try{await send(d);await refresh();setConfirm(null)}catch(e){setError(e instanceof Error?e.message:'Please retry.')}finally{setBusy(false)}}
return <><h1>Safety & moderation</h1><div className="p-panel"><h2>Community rules</h2><p>Discuss books freely, including criticism and low ratings. No harassment, threats, sexual solicitation, exposure of private information, or spam. Mark story spoilers and keep them out of post titles.</p><p>Reports are reviewed by the owner. Basic automatic checks hold suspected spam and selected concerning phrases for review; they cannot understand every context or catch every violation.</p><p>Decisions include an explanation. If a decision affects you, submit an appeal below. Block and mute controls are available beside reader content.</p></div>{error&&<p role="alert">{error} <button onClick={()=>refresh().then(()=>setError('')).catch(e=>setError(e.message))}>Retry</button></p>}{!data&&!error&&<p>Loading…</p>}{data&&<>{data.restriction&&new Date(data.restriction.until)>new Date()&&<div className="p-panel"><h3>Posting temporarily paused</h3><p>Until {new Date(data.restriction.until).toLocaleString()}: {data.restriction.reason}</p></div>}
<h2>{data.user.admin?'Owner review queue':'Decisions & appeals'}</h2>{data.user.admin&&<div className="p-row"><NativeSelect aria-label="Filter cases" value={filter} onChange={e=>setFilter(e.target.value)}><option>Needs review</option><option>All cases</option></NativeSelect><label>Suspension length<NativeSelect value={days} onChange={e=>setDays(e.target.value)}><option value="1">1 day</option><option value="7">7 days</option><option value="30">30 days</option></NativeSelect></label></div>}
{data.cases.filter(c=>!data.user.admin||filter==='All cases'||['open','held'].includes(c.state)||c.appeal_state==='pending').map(c=><article className="p-panel" key={c.id}><small>{c.kind} · {c.state} · {new Date(c.created).toLocaleDateString()}</small><h3>{c.reason}</h3><details><summary>View reported content (may contain spoilers)</summary><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{c.snapshot}</p></details>{c.decision&&<p><b>Decision:</b> {c.decision}</p>}{c.appeal&&<p><b>Appeal ({c.appeal_state}):</b> {c.appeal}</p>}{data.user.admin?<><label>Decision explanation<textarea maxLength={1000} value={text[c.id]||''} onChange={e=>setText({...text,[c.id]:e.target.value})}/></label><div className="p-row">{[['approve','Approve / dismiss'],['remove','Remove content'],['warn','Warn reader'],['suspend','Suspend posting'],['restore','Restore / accept appeal'],['uphold','Uphold decision']].map(([action,label])=><button key={action} disabled={busy||!text[c.id]?.trim()} onClick={()=>setConfirm({action,id:c.id})}>{label}</button>)}</div></>:['held','removed','warned','suspended'].includes(c.state)&&c.appeal_state!=='pending'&&<><label>Why should this be reconsidered?<textarea maxLength={2000} value={text[c.id]||''} onChange={e=>setText({...text,[c.id]:e.target.value})}/></label><button disabled={busy||!text[c.id]?.trim()} onClick={()=>act({action:'appeal',id:c.id,text:text[c.id]})}>Submit appeal</button></>}</article>)}{!data.cases.length&&<p>No decisions or reports to review.</p>}
<h2>Your reports</h2>{data.reports.map(c=><p key={c.id}>{c.kind} · {c.reason} · {c.state}{c.decision?' — '+c.decision:''}</p>)}{!data.reports.length&&<p>You haven’t submitted any reports.</p>}
<h2>Blocked & muted readers</h2>{data.relations.map(r=><div className="p-panel p-row" key={r.other+r.kind}><span>{r.name} · {r.kind==='block'?'Blocked':'Muted'}</span><button disabled={busy} onClick={()=>act({action:'relation',kind:r.kind,other:r.other,value:false})}>{r.kind==='block'?'Unblock':'Unmute'}</button></div>)}{!data.relations.length&&<p>No blocked or muted readers.</p>}</>}
<Dialog open={!!confirm} onOpenChange={v=>!busy&&!v&&setConfirm(null)}><DialogContent className="p-dialog"><DialogTitle>Confirm moderation decision</DialogTitle><DialogDescription>{confirm?.action==='suspend'?'Pause this reader’s posting for '+days+' days.':confirm?.action==='restore'?'Restore this content and lift this reader’s posting restriction.':'Apply this decision to the selected report.'}</DialogDescription><p>{confirm&&text[confirm.id]}</p>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button><button disabled={busy} onClick={()=>confirm&&act({...confirm,reason:text[confirm.id],days:Number(days)})}>{busy?'Saving…':'Confirm decision'}</button></DialogContent></Dialog></>
}
